### ISSUE TITLE
Save x,y coordinates of the landmarks

### ISSUE THREAD

**Issue by jankaWIS** [ddowd97/Python-Image-Morpher#5] opened 2021-04-27 12:11 UTC
Hi, first of all, it's an amazing project of yours. I was reading your documentation and you write there that the user should be also able to upload the (x,y) coordinates of the landmark points. I have not found the option in your GUI. Is it already implemented? And more importantly, would it be possible to add a button for exporting the points into a txt file?
Thanks a lot.

**Comment by ddowd97** [comment] 2021-04-27 13:40
Hello, thanks for your interest in this project!

> the user should be also able to upload the (x,y) coordinates of the landmark points. I have not found the option in your GUI. Is it already implemented?

When you download this repository, it comes with an Images_Points folder that will store whatever this program works with (if this folder gets deleted or moved, it is remade on startup). Currently, if you want to upload a points list, it must be done manually by placing a correctly named text file into Images_Points. Below is an example of an image and it's corresponding text file (with points):

[Dog1.jpg](https://user-images.githubusercontent.com/46535104/116250524-697e7d00-a733-11eb-9a49-2550b6807730.jpg)
[Dog1-jpg.txt](https://github.com/ddowd97/Python-Image-Morpher/files/6384892/Dog1-jpg.txt)

There is no way of doing this with the GUI currently, but since I have been slowly working on a larger update for the project, I may consider adding that to the list of things to do.

> would it be possible to add a button for exporting the points into a txt file?

PIM automatically creates and updates text files in Images_Points as points are placed on images in the GUI, so unless I am misunderstanding what you mean, there is no need for a button like this. :)

**Comment by jankaWIS** [comment] 2021-04-27 14:55
Hi @ddowd97, thanks a lot for your answer. I somehow missed this folder :). No, you didn't miss anything, it was exactly about getting the points out and back in, if the only thing needed is to have them in the directory and get them from there, then it's perfect. I understood that you have to manually locate the files which you want to add.

**Comment by jankaWIS** [comment] 2021-04-29 14:57
Hi @ddowd97 once again, I have now checked it out and I have some issues with it. When you say correctly named, it does not mean (at least in my case) that the name is the same as the picture name. When I tried putting the dog picture together with the txt file into the Image_Points, it did not recognised it. I had to manually rename the file to `janka-jpg.txt` which was the name when I started clicking randomly. It always puts `janka` followed by the ending. It never takes the image name, is it a bug?

Then I have another question. If I put two images and marked the points, only one coordinates were saved, ie. only one file was created. My feeling is that it's because of the aforementioned issue, ie. that both are created but one is being overwritten by the other since they have the same name (since the name of the image does not matter and they're the same, ie. png or jpg). Is it the case? If not, how can I load/add/export them separately?
Thanks.

**Comment by ddowd97** [comment] 2021-04-30 01:25
Following up.

When this project began in early 2019 - when I was first learning Python - I wrote my own regex implementation for catching file names since I didn't know much about the os library. After two years, I believe you have identified an issue with this implemention where, if a file path contains a period before the filename, the regex will trip earlier than intended. 

**Example**: 
/Users/**janka.test**/etc/PIM/Images_Points/Test.jpg → the file name becomes **janka** instead of **Test**

 I have created a hotfixed release to hopefully correct this issue - you can find that release [here](https://github.com/ddowd97/Python-Image-Morpher/releases/tag/v1.1.1). My development branch is messy right now so I can't deploy these changes to the repository, but this hotfix will be included in the next feature update and onwards.

Please let me know if I hit the nail on the head with this analysis and the program works as intended for you.
If not, then as I said before, please provide me details regarding the OS you are using as well as the full file path in use. :)

**Comment by jankaWIS** [comment] 2021-05-02 19:46
I have another issue, I guess very related, this time on Mac. If I load images on Mac, the corresponding files with coordinates which are created are called `Images_Points\image-png.txt` and the folder `Images_Points` is not being created. My guess is / and \ in the path. Because if I have a file called `Images_Points\image-png.txt`, the marks are being loaded. So to sum up -- the folder is not created and probably naming issues with \ and /.

**Comment by ddowd97** [comment] 2021-05-02 20:24
And here I thought I had a working project! ;)
I have created another hotfixed release [here](https://github.com/ddowd97/Python-Image-Morpher/releases/tag/v1.1.2). You are correct in that this bug is due to how operating systems handle directories (I believe Windows may be unique in using the backslash). Although I do not have access to Mac/Linux on a VM currently, I believe this fix will do the trick. Thanks for the bug report, and again, please let me know if you encounter any other issues.

**Closed** 2021-05-09 06:10 UTC
